<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

	public function getTeamsActivities($id)
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->leftJoin('a.teams', 't')
		->addSelect('t')
		->where("t.id = :id")
		->setParameter('id', $id)
		->getQuery()
		->getResult()
		;
		return $qb;
	}

	public function getCurrentActivities()
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->where("a.statusControl = 1")
	    ->orderBy('a.name', 'ASC')
		->getQuery()
		->getResult()
		;
		return $qb;
	}

	public function getHistoricalActivities($year, $month)
	{
		$start = new \DateTime();
		$end = new \DateTime();
		$start->setDate($year, $month, 1);
		$end = $start->format( 'Y-m-t' );

		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->where("( a.endDate IS NOT NULL and a.endDate >= '".$start->format( 'Y-m-d' )."' ) or ( a.endDate IS NULL and a.statusControl = 1 ) ")
        ->andWhere("a.startDate <= '".$end."'")
	    ->orderBy('a.name', 'ASC')
		->getQuery()
		->getResult()
		;
		return $qb;
	}
}
