<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

	public function getTeamsActivities($id)
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->leftJoin('a.teams', 't')
		->addSelect('t')
		->where("t.id = :id")
		->setParameter('id', $id)
		->getQuery()
		->getResult()
		;
		return $qb;
	}
}
