<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EditorEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorEntryRepository extends EntityRepository
{
	public function getEditorEntryId($id)
	{
		$qb = $this
			->createQueryBuilder('a')
			->select("a.id")
			->where("a.inputEntry = :id")
			->setParameter('id', $id)
			->getQuery()
			->getResult(Query::HYDRATE_ARRAY)
  		;
  
		return $qb;
	}

	public function getOverride($id)
	{
		$qb = $this
			->createQueryBuilder('a')
			->select("a")
			->leftJoin('a.editorStatus', 'e')
			->addSelect('e')
			->where("a.inputEntry = :id AND e.id = 1")
			->setParameter('id', $id)
			->setMaxResults(1)
			->getQuery()
			->getOneOrNullResult()
  		;
  
		return $qb;
	}
}
