<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
	public function getAlphaEmployees()
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->leftJoin('a.status', 's')
		->addSelect('s')
		->where("s.id = 1")
        ->orderBy('a.sesa', 'ASC')
		->getQuery()
		->getResult()
		;
		return $qb;
	}

	public function getMaxId()
	{
	    $qb = $this
	    ->createQueryBuilder('s')
	    ->select('MAX(s.id)')
    	->setMaxResults(1)
		->getQuery()
		->getResult()
		;

    return $qb;
	}
}
