<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
	public function getAlphaEmployees()
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->orderBy('a.sesa', 'ASC')
		->getQuery()
		->getResult()
		;

  
		return $qb;
	}
}
