<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * InputEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputEntryRepository extends EntityRepository
{
	public function getEmployeeInputsAtDate($d,$m,$y,$e)
	{
		$date = new \DateTime();
		$date->setDate($y, $m, $d);
		$date->setTime(0, 0, 0);

		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->leftJoin('a.employee', 'e')
		->addSelect('e')
		->where("e.masterId = :eId")
		->leftJoin('a.user_input', 'u')
		->addSelect('u')
		->andWhere("u.dateInput = :date")
        ->addOrderBy('a.id', 'DESC');
        
  		$qb->setParameter('eId', $e);
        $qb->setParameter('date', $date->format('Y-m-d H:i:s'));
		
		return $qb->getQuery()->getResult();
	}

	public function getEntryArray($id)
	{
		$qb = $this
			->createQueryBuilder('a')
			->select("a.sesa, a.present, a.comments")
			->leftJoin('a.employee', 'e')
			->addSelect('e.id as employee')
			->leftJoin('a.absence_reason', 'ar')
			->addSelect('ar.id as absence')
			->leftJoin('a.activity_hours', 'ah')
			->addSelect('ah.id as activity_hours, ah.regularHours, ah.otHours')
			->leftJoin('ah.activity', 'act')
			->addSelect('act.id as activity')
			->where("a.id = :id")
			->setParameter('id', $id)
			->getQuery()
			->getResult(Query::HYDRATE_ARRAY)
  		;
  
		return $qb;
	}
}
