<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
	public function getReportingTeams()
	{
		$qb = $this
		->createQueryBuilder('a')
		->select("a")
		->where("a.name <> 'VTeam'")
		->getQuery()
		->getResult()
		;
		return $qb;
	}
}
