<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserInputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInputRepository extends EntityRepository
{
	public function getLastMonth()
	{
		$now = new \DateTime();
		$lastMonth = new \DateTime();
		$lastMonth->modify( '-'.(date('j')).' day' );

		$qb = $this
			->createQueryBuilder('a')
			->select("a")
			->where("a.dateInput <= '".$now->format("Y-m-d H:i:s")."'")
            ->andWhere("a.dateInput > '".$lastMonth->format("Y-m-d H:i:s")."'")
		    ->orderBy('a.dateInput', 'DESC')
			->getQuery()
			->getResult()
  		;
  
		return $qb;
	}

	public function getMonthInputs($month, $year)
	{
		$start = new \DateTime();
		$end = new \DateTime();
		$start->setDate($year, $month, 1);
		$end = $start->format( 'Y-m-t H:i:s' );
		$start->modify( '-1 day' );

		$qb = $this
			->createQueryBuilder('a')
			->select("a")
			->where("a.dateInput <= '".$end."'")
            ->andWhere("a.dateInput > '".$start->format("Y-m-d H:i:s")."'")
		    ->orderBy('a.dateInput', 'ASC')
			->getQuery()
			->getResult()
  		;
  
		return $qb;
	}
}
