<?php

namespace SE\InputBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserInputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInputRepository extends EntityRepository
{
	public function getLastMonth()
	{
		$now = new \DateTime();
		$lastMonth = new \DateTime();
		$lastMonth->modify( '-'.(date('j')-1).' day' );

		$qb = $this
			->createQueryBuilder('a')
			->select("a")
			->where("a.date< '".$now->format("Y-m-d H:i:s")."'")
            ->andWhere("a.date > '".$lastMonth->format("Y-m-d H:i:s")."'")
		    ->orderBy('a.dateInput', 'DESC')
			->getQuery()
			->getResult()
  		;
  
		return $qb;
	}
}
