se_admin_index:
    path:     /
    defaults: { _controller: SEAdminBundle:Admin:index }

se_admin_editor:
    path:     /editor
    defaults: { _controller: SEAdminBundle:Editor:editor }

se_admin_import_sap:
    path:     /import
    defaults: { _controller: SEAdminBundle:Import:sap }

se_admin_editor_currentEntry:
    pattern:  /editor/currentEntry
    defaults: { _controller: SEAdminBundle:Editor:currentEntry }
    requirements:
        _method:  GET

se_admin_editor_accept:
    pattern:  /editor/accept
    defaults: { _controller: SEAdminBundle:Editor:accept }
    requirements:
        _method:  POST

se_admin_editor_reject:
    pattern:  /editor/reject
    defaults: { _controller: SEAdminBundle:Editor:reject }
    requirements:
        _method:  POST

se_admin_editor_ignore:
    pattern:  /editor/ignore
    defaults: { _controller: SEAdminBundle:Editor:ignore }
    requirements:
        _method:  POST

se_admin_import_delete:
    pattern:  /import/delete
    defaults: { _controller: SEAdminBundle:Import:delete }
    requirements:
        _method:  POST