<?php

namespace SE\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttendanceDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceDataRepository extends EntityRepository
{
}
