<?php

namespace SE\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
	public function getMonth($month, $year)
	{
		$qb = $this
			->createQueryBuilder('a')
			->select("a")
			->where("a.m = '".$month."' AND a.y = '".$year."'")
            ->orderBy('a.dt', 'ASC')
			->getQuery()
			->getResult()
  		;
  
		return $qb;
	}
}
