<?php

namespace SE\ZestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationsWithAdvert($limit)
	{
		$qb = $this
			->createQueryBuilder('a')
			->join('a.advert', 'adv')
  			->addSelect('adv')
  			->setMaxResults($limit)
  			;
  
		return $qb
		->getQuery()
		->getResult()
		;
	}
}
